### ISSUE TITLE
Adjust mapping to match SF picklist values

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/Norwegian-Refugee-Council#1]
In `projectsWithFinancials.js` we need to adjust the mapping to match the expected SF picklist values:
```js
{ INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST: Agresso Project Cycle: bad value for restricted picklist field: 9
    at HttpApi.getError (/home/taylor/language-packages/language-salesforce/node_modules/jsforce/lib/http-api.js:250:13)
    at /home/taylor/language-packages/language-salesforce/node_modules/jsforce/lib/http-api.js:95:22
    at /home/taylor/language-packages/language-salesforce/node_modules/promise/lib/core.js:33:15
    at flush (/home/taylor/language-packages/language-salesforce/node_modules/promise/node_modules/asap/asap.js:27:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST',
  errorCode: 'INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST',
  fields: [ 'Agresso_Project_Cycle__c' ] }
```

**Comment by CarolErnst** [comment]
@taylordowns2000 Made the picklist unrestricted, unfortunately there is no clear reference list of all the values. I think we can explore that in SF and then adjust the filter on Project Cycle later if needed. Right now I believe we're only filtering out projects with Project Cycle = 1 OR 2.

**Comment by taylordowns2000** [comment]
That worked. Thanks, @CarolErnst . We can, in the future, change the job to modify the values coming from Agresso to whatever you'd like to see in SF. For now, it runs just fine.
